<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.7 /home/godzy/projects/fohoov-portfolio/static/threlte/models/FlashLight.glb --root /threlte/models/ --types --printwidth 120 --precision 2
Author: SketchyBot (https://sketchfab.com/halonerd88)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flashlight-4776f56179af4891ac856316892c4cd8
Title: Flashlight
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group | undefined }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Cylinder_Material_0: THREE.Mesh;
		};
		materials: {
			Material: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/threlte/models/FlashLight.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={0.24}>
			<T.Group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
				<T.Mesh
					geometry={gltf.nodes.Cylinder_Material_0.geometry}
					material={gltf.materials.Material}
					rotation={[0, 0, -Math.PI / 2]}
					scale={100} />
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
